version: '3.8'

services:
  buddy_up_app:
    image: buddy_up_app:latest
    build: ./src/
    command: gunicorn --bind 0.0.0.0:5000 application:create_app()
    container_name: buddy_up_app
    ports:
      - 8080:8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: