version: "3.8"

services:
  buddy_up_app:
    image: buddy_up_app:latest
    build: 
      context: ./src/
      dockerfile: Dockerfile
    container_name: buddy_up_app
    ports:
      - 8080:8080
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: buddySecret
      POSTGRES_USER: buddyPostgres
      POSTGRES_DB: buddyDB
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    

