version: "3.8"

services:
  buddy_up_app:
    image: buddy_up_app:latest
    build: 
      context: ./src/
      dockerfile: Dockerfile
    container_name: buddy_up_app
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    

